categorical_column:
  Customer_Information:
  - Working Class
  - Wealthy
  Express_Shipment:
  - 'No'
  - 'Yes'
  Fragile:
  - 'Yes'
  - 'No'
  Installation_Included:
  - 'No'
  - 'Yes'
  International:
  - 'Yes'
  - 'No'
  Material:
  - Clay
  - Stone
  - Brass
  - Wood
  - Marble
  - Aluminium
  - Bronze
  Remote_Location:
  - 'No'
  - 'Yes'
numerical_columns:
- Artist_Reputation
- Height
- Width
- Weight
- Price_Of_Sculpture
- Base_Shipping_Price
